### ISSUE TITLE
can not support libsvm format data train/predict

### ISSUE THREAD

**Issue by lizhangzhan** [huawei-noah/streamDM-Cpp#1]
When compare the streamDM-Cpp with other online algorithm, in our internal dataset,  we found this library indeed can not support libsvm format data input.  With further debugging,   SpareInstance Class hasn't implemented completely.

**Comment by lizhangzhan** [comment]
I am not sure whether this version is newest, or it has been implemented in your development version.

**Comment by smaniu** [comment]
The current implementation does not contain the LibSVM format exactly, it contains a variation of it. Due to the way `Example` is defined internally, the input (features) and output (label) is separated by a whitespace, whereas within the input/output instance the features are separated by a comma.
Details here http://huawei-noah.github.io/streamDM/docs/Programming.html

**Comment by abifet** [comment]
What did you find that it is missing in SparseInstance?

**Comment by lizhangzhan** [comment]
SparseInstance::clone() has not implemented.  But,  in Instace.cpp: cloneInstance() function, it is called.

**Comment by abifet** [comment]
Thanks! Yes, SparseInstance::clone() has not been implemented yet. StreamDM-cpp
has been tested with dense instances, and sparse instances are still under
development. Would you like to contribute to the project helping on this?
